const disableTypes = [
    {
        type: '청각 장애인',
        company: '주식회사 케이비손해보험',
        title: 'KB 손해보험 8시간 근무 청약서심사직원 채용',
        salary: '월급 207만원',
        deadline: 20,
        iconURL: '/logo/kb.jpg',
    },
    {
        type: '시각 장애인 제외',
        company: '법무법인(유한) 화우',
        title: '[법무법인(유한) 화우][법무법인 화우] 문서수발직 장애인 직원 채용(채용시 마감)',
        salary: '월급 103만원',
        deadline: 13,
        iconURL: '/logo/hwawoo.png',
    },
    {
        type: '시각 장애인',
        company: '씨제이프레시웨이주식회사',
        title: '[씨제이프레시웨이주식회사]CJ프레시웨이 단체급식 보조 (시간대별 1명씩 총 2명, 채용 시 마감)',
        salary: '시급 9,860원',
        deadline: 34,
        iconURL: '/logo/cj.png',
    },
    {
        type: '청각 장애인',
        company: '중앙대학교광명병원',
        title: '[중앙대학교광명병원]중앙대학교 광명병원 간호본부 사무보조 채용공고',
        salary: '월급 230만원',
        deadline: 8,
        iconURL: '/logo/jungang.jpg',
    },
    {
        type: '청각 장애인',
        company: '주식회사 케이비손해보험',
        title: 'KB 손해보험 8시간 근무 청약서심사직원 채용',
        salary: '103만원',
        deadline: 8,
        iconURL: '/logo/kb.jpg',
    },
    {
        type: '청각 장애인',
        company: '주식회사 케이비손해보험',
        title: 'KB 손해보험 8시간 근무 청약서심사직원 채용',
        salary: '103만원',
        deadline: 8,
        iconURL: '/logo/kb.jpg',
    },
    {
        type: '청각 장애인',
        company: '주식회사 케이비손해보험',
        title: 'KB 손해보험 8시간 근무 청약서심사직원 채용',
        salary: '103만원',
        deadline: 8,
        iconURL: '/logo/kb.jpg',
    },
    {
        type: '청각 장애인',
        company: '주식회사 케이비손해보험',
        title: 'KB 손해보험 8시간 근무 청약서심사직원 채용',
        salary: '103만원',
        deadline: 8,
        iconURL: '/logo/kb.jpg',
    },
    {
        type: '청각 장애인',
        company: '주식회사 케이비손해보험',
        title: 'KB 손해보험 8시간 근무 청약서심사직원 채용',
        salary: '103만원',
        deadline: 8,
        iconURL: '/logo/kb.jpg',
    },
    {
        type: '청각 장애인',
        company: '주식회사 케이비손해보험',
        title: 'KB 손해보험 8시간 근무 청약서심사직원 채용',
        salary: '103만원',
        deadline: 8,
        iconURL: '/logo/kb.jpg',
    },
    {
        type: '청각 장애인',
        company: '주식회사 케이비손해보험',
        title: 'KB 손해보험 8시간 근무 청약서심사직원 채용',
        salary: '103만원',
        deadline: 8,
        iconURL: '/logo/kb.jpg',
    },
    {
        type: '청각 장애인',
        company: '주식회사 케이비손해보험',
        title: 'KB 손해보험 8시간 근무 청약서심사직원 채용',
        salary: '103만원',
        deadline: 8,
        iconURL: '/logo/kb.jpg',
    },
    {
        type: '청각 장애인',
        company: '주식회사 케이비손해보험',
        title: 'KB 손해보험 8시간 근무 청약서심사직원 채용',
        salary: '103만원',
        deadline: 8,
        iconURL: '/logo/kb.jpg',
    },
];

export default disableTypes;